sudo: required
dist: precise
language: android

jdk:
  - oraclejdk8

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

android:
  components:
  - tools
  - platform-tools
  - android-25
  - build-tools-25.0.2
  - extra-android-m2repository
  - extra-google-m2repository
  - extra-google-google_play_services
  licenses:
  - android-sdk-license-[0-9a-f]{8}
script: ./scripts/buildApp.sh
before_deploy:
 - openssl aes-256-cbc -K $encrypted_218b70c0d15d_key -iv $encrypted_218b70c0d15d_iv -in scripts/rtd.jks.enc -out scripts/rtd.jks -d
 - ./scripts/before_deploy.sh
env:
  global:
  - secure: GeIi5Obx4J1EqDpA5lnRhF2i0vjJj9SCXzbiSbyiy6gWo9/SuoV4QF46VJVMMU2cfD6b4Y4x6MlbnWnGD+8w3vqMLRN9gJxBukdv8fe8FHXLC2VYOi5lBQHAPip0KaqDlLTMp6U0tKD/2/y7FGXWNbu651SvjOzmwlDBiC0xKaM=
  - secure: oIgx29UwqqHlv1y3+Egh1ojXAdktTqNSZjcA4n/k9S9aXfDqw8XMsbDt3VY9yQPZXuRug6aOkTLSanlC+4IajcGX9fM6/3Va1bSpCt8bkWGVXA2enHyEEoVy6s/LfJmuD8lpIltr0yeKafQp6RU61xmqlEtw9DggxI0shg60d14=
  - secure: iT32cHpCue2TJvME/tJYjWR1TbyPJnTXzdaAuQ8FnIkZWBPhsWPZ5KLeUvsAKnsohSaD/qMw68s/NpEI9emob6xdsmML2IvyMK3EL7e8t60xnyYOM1RGOZXoP7XQ7G8+DB7GLx1O8YjNlAPQhR7LcoNKa9cKQ4iox0JfhQMM/BM=
  - secure: "F09QUU7fDOZ9tIjB8k83s5PZYynIe6HI1ZxfUByTs1y6qnZvr40bBaI0hm7bNTcBDvtqhZuxxmuDCr29KWLDN1QH6ExJTUIx2ocAQ4kP9x2t2wr+eoMF19QQeNwqXZuvTa58EFA096hglom5/wLxdKsL8JjskRHekn2ARcK5ank="
deploy:
  provider: releases
  api_key:
    secure: MNBI+eK7Aa4BCucvmxzzVlm/Tc4fyqdjv1iu5IqtjJc4vFUE3LvjBJ9d/lsQD89eavj8STMyONhbQ2+6JL6EKrfhulwwMVd5N//daLO9KA/xfEpIZO9z9RvP5VdqTDDTYrJ52HrB/MC+v5AqxxZUfk7XVjxRmAvefGWhVtlZ8CY=
  file:
    - ./app/build/outputs/apk/app-debug.apk
    - ./app/build/outputs/apk/app-release.apk
  on:
    repo: zendesk/sdk_demo_app_android
    tags: true
